# action.yml
name: 'K3D Cluster'
description: 'Create or destroy a k3d cluster'
inputs:
  cluster_action:  # id of input
    description: 'Create or destroy'
    required: true
    default: create
  aws_assume_role:  # id of input
    description: 'role for the identity provider to assume'
    required: false
    default: ""
  aws_region:  # id of input
    description: 'aws region'
    required: false
    default: "us-west-2"
outputs:
  instance_id: # id of output
    description: 'instance_id of the cluster'
    value: ${{ steps.create_cluster.outputs.instance_id }}
  secret_name: # id of output
    description: 'instance_id of the cluster'
    value: ${{ steps.create_cluster.outputs.secret_name }}
  sha: # id of output
    description: 'sha of the cluster'
    value: ${{ steps.create_cluster.outputs.sha }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      if: ${{ inputs.aws_assume_role != '' }} 
      with:
        role-to-assume: ${{ inputs.aws_assume_role }}
        role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
        aws-region: ${{ inputs.aws_region }}
        role-duration-seconds: 21600
    - name: Create cluster
      id: create_cluster
      env:
        SHA: ${{ github.sha }}
      if: ${{ inputs.cluster_action == 'create' }} 
      working-directory: ${{ github.action_path }}/terraform
      run: |
        ${{ github.action_path }}/terraform/create-cluster.sh
        echo "instance_id=$(terraform output -raw instance_id)" >> $GITHUB_OUTPUT
        echo "secret_name=$(terraform output -raw secret_name)" >> $GITHUB_OUTPUT
        echo "sha=${SHA}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Teardown cluster
      if: ${{ inputs.cluster_action == 'destroy' }} 
      shell: bash
      env:
        SHA: ${{ github.sha }}
      working-directory: ${{ github.action_path }}/terraform
      run: ${{ github.action_path }}/terraform/teardown-cluster.sh
