# action.yml
name: 'K3D Cluster'
description: 'Create or destroy a k3d cluster'
inputs:
  cluster_action:  # id of input
    description: 'Create or destroy'
    required: true
    default: create
  aws_assume_role:  # id of input
    description: 'role for the identity provider to assume'
    required: true
outputs:
  instance_id: # id of output
    description: 'instance_id of the cluster'
  secret_name: # id of output
    description: 'instance_id of the cluster'
  sha: # id of output
    description: 'sha of the cluster'
runs:
  using: "composite"
  steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws_assume_role }}
        role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
        aws-region: us-west-2
        role-duration-seconds: 21600
    - name: Create cluster
      if: ${{ inputs.cluster_action == 'create' }} 
      working-directory: ${{ github.action_path }}/terraform
      run: ${{ github.action_path }}/terraform/create-cluster.sh
      env:
        SHA: ${{ github.sha }}
      shell: bash
    - name: Teardown cluster
      if: ${{ inputs.cluster_action == 'destroy' }} 
      shell: bash
      env:
        SHA: ${{ github.sha }}
      working-directory: ${{ github.action_path }}/terraform
      run: ${{ github.action_path }}/terraform/teardown-cluster.sh
      
#runs-on: ubuntu-latest
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.who-to-greet }}
