name: "Build AMI"

on:
  schedule:
    - cron: "0 5 * * *"

  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "**.md"

jobs:
  build-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: us-west-2
          # 21600 seconds == 6 hours
          role-duration-seconds: 21600

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Packer init
        run: packer init .
        working-directory: packer

      - name: Packer build
        run: packer build .
        working-directory: packer
