name: "Test UDS k3d CI infra"

on:
  push:


permissions:
  id-token: write
  contents: read

jobs:
  test-k3d-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: create_cluster
        uses: defenseunicorns/uds-aws-ci-k3d@action
        with:
          cluster_action: create
          aws_assume_role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - name: destroy_cluster
        uses: defenseunicorns/uds-aws-ci-k3d@action
        with:
          cluster_action: destroy
          aws_assume_role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
