name: "Test UDS k3d CI infra"

on:
  push:
    branches:
      - "main"
    paths:
      - "terraform/**"
      - ".github/**"

  pull_request:
    branches:
      - "main"
    paths:
      - "terraform/**"
      - ".github/**"

permissions:
  id-token: write
  contents: read

jobs:
  test-k3d-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: us-west-2
          # 21600 seconds == 6 hours
          role-duration-seconds: 21600

      - name: Install Zarf
        # This uses the default options (latest version of zarf, no init package)
        uses: defenseunicorns/setup-zarf@main

      - name: Create cluster
        env:
          SHA: ${{ github.sha }}
        run: ./create-cluster.sh
        working-directory: terraform

      - name: Teardown cluster
        if: always()
        env:
          SHA: ${{ github.sha }}
        run: ./teardown-cluster.sh
        working-directory: terraform
